// # Proxy Compiler 18.9.4-973a4d-20181128

import Foundation
import SAPOData

internal class GetFieldTicketDetailsStaticResolver {
    static func resolve() {
        GetFieldTicketDetailsStaticResolver.resolve1()
    }

    private static func resolve1() {
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntityTypes.attachmentsType)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntityTypes.changeLogsType)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntityTypes.commentsType)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntityTypes.dftHeaderType)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntitySets.attachments)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntitySets.changeLogs)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntitySets.comments)
        Ignore.valueOf_any(GetFieldTicketDetailsMetadata.EntitySets.dftHeader)
        Ignore.valueOf_any(AttachmentsType.attachmentID)
        Ignore.valueOf_any(AttachmentsType.dftNumber)
        Ignore.valueOf_any(AttachmentsType.attachmentName)
        Ignore.valueOf_any(AttachmentsType.dftAttachmentType)
        Ignore.valueOf_any(AttachmentsType.createdByName)
        Ignore.valueOf_any(AttachmentsType.createdOn)
        Ignore.valueOf_any(AttachmentsType.updatedByName)
        Ignore.valueOf_any(AttachmentsType.updatedOn)
        Ignore.valueOf_any(AttachmentsType.attachmentUrl)
        Ignore.valueOf_any(ChangeLogsType.activityID)
        Ignore.valueOf_any(ChangeLogsType.dftNumber)
        Ignore.valueOf_any(ChangeLogsType.status)
        Ignore.valueOf_any(ChangeLogsType.createdOn)
        Ignore.valueOf_any(ChangeLogsType.createdByName)
        Ignore.valueOf_any(CommentsType.commentID)
        Ignore.valueOf_any(CommentsType.dftNumber)
        Ignore.valueOf_any(CommentsType.commentedByName)
        Ignore.valueOf_any(CommentsType.commentedOn)
        Ignore.valueOf_any(CommentsType.comment)
        Ignore.valueOf_any(DFTHeaderType.dftNumber)
        Ignore.valueOf_any(DFTHeaderType.poNumber)
        Ignore.valueOf_any(DFTHeaderType.vendorAdminID)
        Ignore.valueOf_any(DFTHeaderType.vendorID)
        Ignore.valueOf_any(DFTHeaderType.vendorName)
        Ignore.valueOf_any(DFTHeaderType.vendorAddress)
        Ignore.valueOf_any(DFTHeaderType.aribaSesNo)
        Ignore.valueOf_any(DFTHeaderType.serviceProviderMail)
        Ignore.valueOf_any(DFTHeaderType.serviceProviderID)
        Ignore.valueOf_any(DFTHeaderType.serviceProviderName)
        Ignore.valueOf_any(DFTHeaderType.reviewerID)
        Ignore.valueOf_any(DFTHeaderType.reviewerName)
        Ignore.valueOf_any(DFTHeaderType.reviewerEmail)
        Ignore.valueOf_any(DFTHeaderType.sesApproverName)
        Ignore.valueOf_any(DFTHeaderType.sesApproverEmail)
        Ignore.valueOf_any(DFTHeaderType.department)
        Ignore.valueOf_any(DFTHeaderType.location)
        Ignore.valueOf_any(DFTHeaderType.startDate)
        Ignore.valueOf_any(DFTHeaderType.startTime)
        Ignore.valueOf_any(DFTHeaderType.endDate)
        Ignore.valueOf_any(DFTHeaderType.endTime)
        Ignore.valueOf_any(DFTHeaderType.accountingCategory)
        Ignore.valueOf_any(DFTHeaderType.costCenter)
        Ignore.valueOf_any(DFTHeaderType.sesNumber)
        Ignore.valueOf_any(DFTHeaderType.workOrderNo)
        Ignore.valueOf_any(DFTHeaderType.signatureVersion)
        Ignore.valueOf_any(DFTHeaderType.wbsElement)
        Ignore.valueOf_any(DFTHeaderType.deviceType)
        Ignore.valueOf_any(DFTHeaderType.deviceID)
        Ignore.valueOf_any(DFTHeaderType.status)
        Ignore.valueOf_any(DFTHeaderType.createdBy)
        Ignore.valueOf_any(DFTHeaderType.createdOn)
        Ignore.valueOf_any(DFTHeaderType.updatedBy)
        Ignore.valueOf_any(DFTHeaderType.updatedOn)
        Ignore.valueOf_any(DFTHeaderType.vendorRefNumber)
        Ignore.valueOf_any(DFTHeaderType.reviewedOn)
        Ignore.valueOf_any(DFTHeaderType.reviewedBy)
        Ignore.valueOf_any(DFTHeaderType.completedBy)
        Ignore.valueOf_any(DFTHeaderType.completedOn)
        Ignore.valueOf_any(DFTHeaderType.well)
        Ignore.valueOf_any(DFTHeaderType.field)
        Ignore.valueOf_any(DFTHeaderType.facility)
        Ignore.valueOf_any(DFTHeaderType.wellPad)
        Ignore.valueOf_any(DFTHeaderType.ownerID)
        Ignore.valueOf_any(DFTHeaderType.wfInstanceID)
        Ignore.valueOf_any(DFTHeaderType.comments)
        Ignore.valueOf_any(DFTHeaderType.changeLogs)
        Ignore.valueOf_any(DFTHeaderType.attachments)
    }
}
